# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "AIFengheshu"
repo_name: "Attention-Mechanism-arXiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 1000

publish_readme: True
publish_gitpage: True
publish_wechat: True

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Attention": 
        filters: ["Attention", "Attention Mechanism"]
    "IRSTD": 
        filters: ["Infrared small target detection", "Infrared small target segmentation", "IRSTD", "NUDT-SIRST", "NUAA-SIRST", "IRSTD-1K"]
    "UNet": 
        filters: ["UNet", "U-Net", "medical image segmentation"]
